# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sagely Go...
description: > # this means to ignore newlines until "baseurl:"
  Words of wisdom, or not; Thoughts to mull about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sagely.ca" # the base hostname & protocol for your site
twitter_username: sage905
github_username:  sage905

# Build settings
markdown: kramdown
safe: true
timezone: America/Toronto

