# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sagely Go...
description: > # this means to ignore newlines until "baseurl:"
  Words of wisdom, or not; Thoughts to mull about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sagely.ca" # the base hostname & protocol for your site
twitter_username: sage905
github_username:  sage905
permalink: :title

# Build settings
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
timezone: America/Toronto

#Theme config
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/sage905', 'fa-user']
single_footer: '<p>&copy; 2017 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Sagely', '/about']

defaults:
  -
    scope:
      path: ""
    values:
      comments: true
      author_name: Sage905
      author_url: author/Sage905
      author_avatar: sage
      show_avatar: true
      show_related_posts: true
      feature_image: feature-sailing
      square_related: recommend-wolf
